services:
  server:
    image: localhost:5000/fca-server:1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    env_file:
      - ./server/.env

  client:
    image: localhost:5000/fca-client:1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    env_file:
      - ./client/.env
