name: fca-app

services:
  backend-service:
    build: ./server
    expose:
      - "7777"
    ports:
      - "5001:7777"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1:5001/api/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5a

  client:
    build: ./client
    ports:
      - "5173:80"
    environment:
      - BACKEND_HOST=server
      - BACKEND_PORT=7777


