name: fca-app
on:
  push:
    branches:
      - main
      - "learning/*"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.changes.outputs.server }}
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: detect changes
        id: changes
        uses: tj-actions/changed-files@v46.0.1 # Upgraded for security/features
        with:
          files_yaml: |
            server:
              - 'server/**'
            client:
              - 'client/**'
  debug:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: debug outputs
        run: |
          echo "Server changes: ${{ needs.detect-changes.outputs.server }}"
          echo "Client changes: ${{ needs.detect-changes.outputs.client }}"
          echo "Changed files"

  # build-push:
  #   runs-on: ubuntu-latest
  #   needs: detect-changes
  #   steps:
  #     - name: checkout repository
  #       uses: actions/checkout@v4
  #     - name: log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #     - name: build server image
  #       if: needs.detect-changes.outputs.server == 'true'
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./
  #         file: ./server/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/fca-server:${{ github.sha }}
  #     - name: build client image
  #       if: needs.detect-changes.outputs.client == 'true'
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./client
  #         file: ./client/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/fca-client:${{ github.sha }}
